FROM python:3.7-alpine

ENV PYTHONUNBUFFERED=1


RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && apk add --no-cache --virtual .build-deps gcc g++ make libffi-dev openssl-dev linux-headers python3-dev postgresql-dev musl-dev

COPY ./requirements.txt /requirements.txt

RUN pip install psycopg2

RUN pip install -r requirements.txt

RUN apk del .build-deps

COPY ./docker/gunicorn.sh /gunicorn.sh
RUN sed -i 's/\r//' /gunicorn.sh
RUN chmod +x /gunicorn.sh

WORKDIR /opt